### PR TITLE
selection after delete

### PR DESCRIPTION
**Pull request by fuchsmich**
I have no idea how to use rebase or whatever...

### CODE REVIEW

**Comment by oroulet** [comment]
git pull --rebase origin qml instead of simply pull

**Comment by oroulet** [comment]
another solution is to simply checkout master and use git cherry-pick xxxxxxcommitxxx
git is very very usefull, but I agree it takes some time to get used to it..

**Comment by fuchsmich** [comment]
I found this guide: https://gist.github.com/Chaser324/ce0505fbed06b947d962
But I can't create a workflow, that works for me.

**Comment by oroulet** [comment]
this guide really make it complicated

to make a new feature
git checkout -b mynewbranch
do your work
git commit -m "my fancy work"
git pull -r origin master  # to update for any changes from master UNDER our work
make PR

and to start working again
git checkout master # back to master
git checkout -b my new feature
etc....
#
btw we do not have master in that reposittory, it is called qml. I should fix that

**Comment by fuchsmich** [comment]
ok, thank you, sounds good.

> btw we do not have master in that reposittory, it is called qml. I should fix that

...yes this was of course caused by me. ;)

**Comment by fuchsmich** [comment]
...and i think we can delete .gitmodules

**Comment by oroulet** [comment]
What is that file about?

**Comment by fuchsmich** [comment]
It's left over from the Theme-submodul.

**Pull request closed without merging**
