### PR TITLE
define calendar keywords in qml

### PR DESCRIPTION
**Pull request by fuchsmich**
Thats what i meant in the comments of alst commit.

### CODE REVIEW

**Comment by oroulet** [comment]
but why? Now we have completion words defined at 2 different places.

**Comment by fuchsmich** [comment]
So what? We defined it before in *three* different places...

The keywords for calendar popup are defined in *one* place now.
Of course we can define them in python, but then we need to export them to qml. 
If you prefer this, ok.

**Comment by oroulet** [comment]
What about rec: (and h:1) they are also keyword that should be completed but not put a date after. Word Completion and poping calendar is not exactly the same

**Comment by oroulet** [comment]
There is something wrong in that PR. I think it should have worked with a simple git pull --rebase. Now you probably need to make a new branch from master and cherry-pick your commits. Or do a big rebase

**Comment by fuchsmich** [comment]
yes, this is very annoying.

**Pull request closed without merging**
