### PR TITLE
README: Install two more packages for error-free ubuntu install

### PR DESCRIPTION
**Pull request by alvcap**

### CODE REVIEW

**Comment by topas-rec** [comment]
OK thanks. Let me know if you have issues.

**Comment by alvcap** [comment]
It now builds and installs fine on a fresh ubuntu 18.04 installation. I have also edited https://github.com/QTodoTxt/QTodoTxt2/blob/master/packaging/Debian/buildDebPackage.py in order to pack qtodotxt2, maybe you would like to check if my naming assumptions are correct..

**Comment by topas-rec** [comment]
Thanks!
I'll test this one and then compare to #102 before, because it it related.

**Comment by alvcap** [comment]
Done, I kept your changes

**Comment by topas-rec** [comment]
Ie thanks. Ready for merge.
One thing: You reverted your changes from e879b580. I thought they look good, though I had problems with existing files during build of deb package (I would go through this again)

To you want to add the changes from commit e879b580 here again or should we keep it as is? (Just dependencies adding)

**Comment by alvcap** [comment]
The error I tried to fix with e879b580c5878be2766cb857fe1d937d0c5a7636 does not occur when I use your version of buildDebPackage.py , maybe I assumed some incorrect namings and experienced an error created by me alone. I think that we can drop my changes and continue with your version.

**Pull request merged**
