### PR TITLE
Consequently importing QtQuick version 2.5 instead of mixing 2.5 and 2.7

### PR DESCRIPTION
**Pull request by topas-rec**
Does it work on your platforms?
Should I do this for the other branches too?

### CODE REVIEW

**Comment by oroulet** [comment]
why is that PR on multi branch? The main branch was qml but I just changed it to be master as it is the expected name

**Comment by topas-rec** [comment]
I don't know how to find the default branch. I'll switch this to qml.

**Comment by oroulet** [comment]
No. Change to master

**Comment by oroulet** [comment]
@topas-rec  merged manually to master since it was created against wrong branch

**Pull request closed without merging**
