### PR TITLE
Make threshold date recur correctly the first time

### PR DESCRIPTION
**Pull request by topas-rec**
@sttrebo: Can you test this and give some feedback if this help with issue #86 ?

### CODE REVIEW

**Comment by sttrebo** [comment]
here's the output of the todo.txt (example) file.  All I did was to mark those line itmes as done repeatedly.  note that the dates do not increment at all.

(A) Make peace between Cylons and humans +PeaceProject
(B) Report to <i>Admiral Adama</i> about FTL @CIC +GalacticaRepairs due:2013-05-24
(C) 2016-12-08 Feed Schrodinger's Cat rec:+1d due:2014-02-23
(C) Upgrade jump drives with Cylon technology +GalacticaRepairs
+(A) Review NCMR Log +Admin @work t:2018-03-28 rec:+1b due:2018-03-28
+Find the question due:2017-06-10 rec:6d t:2017-06-09
+x 2016-02-21 (B) Seal ship's cracks with biomatter +GalacticaRepairs
+x 2018-03-27 (A) Review NCMR Log +Admin @work t:2018-03-28 rec:+1b due:2018-03-28
-Find the question due:2018-04-02 rec:6d t:2018-04-02
-x 2016-02-21 (B) Seal ship's cracks with biomatter +GalacticaRepairs
2016-12-12 +GalacticaRepairs Check hull integrity rec:+7b due:2016-12-12
Check for <b>DRADIS</b> contact @CIC
Check if http://google.com is available
Download code from <br/> https://github.com/QTodoTxt/QTodoTxt/archive/master.zip <br/>and give it a try!
Think about <u>future</u> t:2099-12-31
h:1 @CIC +GalacticaRepairs @work
x 2018-03-27 +x 2018-03-27 (A) Review NCMR Log +Admin @work t:2017-12-22 rec:+1b due:2017-12-22
x 2018-03-27 +x 2018-03-27 (A) Review NCMR Log +Admin @work t:2018-03-28 rec:+1b due:2018-03-28
x 2018-03-27 +x 2018-03-27 (A) Review NCMR Log +Admin @work t:2018-03-28 rec:+1b due:2018-03-28
x 2018-03-27 +x 2018-03-27 (A) Review NCMR Log +Admin @work t:2018-03-28 rec:+1b due:2018-03-28
x 2018-03-27 +x 2018-03-27 (A) Review NCMR Log +Admin @work t:2018-03-28 rec:+1b due:2018-03-28
x 2018-03-27 +x 2018-03-27 (A) Review NCMR Log +Admin @work t:2018-03-28 rec:+1b due:2018-03-28
x 2018-03-27 -Find the question due:2017-06-10 rec:6d t:2017-06-09
x 2018-03-27 -Find the question due:2018-04-02 rec:6d t:2017-06-10
x 2018-03-27 -Find the question due:2018-04-02 rec:6d t:2018-04-02
x 2018-03-27 -Find the question due:2018-04-02 rec:6d t:2018-04-02

**Comment by topas-rec** [comment]
I see. I'll test this and try to fond the cause.

**Comment by topas-rec** [comment]
Correction:
The original problem in #86 was:
@sttrebo :

> hmmm, i had some strange behavior when i used it.

> (A) Review NCMR Log

> +Admin @work t:2017-12-22 rec:+1d due:2017-12-22 - works fine, both due and threshold increment properly

>if I change the d to a b then mark the task as done, I get this:
(A) Review NCMR Log +Admin @work t:2017-12-22 rec:+1b due:2017-12-25

>then if I mark it as done again I get this:
(A) Review NCMR Log +Admin @work t:2017-12-25 rec:+1b due:2017-12-25

>it seems that with the 'b', the due and threshold dates don't increment properly.

First time on completing the task the threshold date did not increment, but the due date did.
Second time the threshold date also incremented, but the due date did not.
It seems that one issue is fixed, since the threshold date increments the first time you completed the task in this pull request #95 .

There is a second wrong behaviour where the due date of tasks that recur on business days does not increment.

**Comment by topas-rec** [comment]
I'll take a look at this.

**Comment by topas-rec** [comment]
@sttrebo @oroulet 

The problem above left in this PR
> There is a second wrong behaviour where the due date of tasks that recur on business days does not increment.

should be discussed.

At first: The task
`(A) Review NCMR Log +Admin @work t:2018-03-28 rec:+1b due:2018-03-28`
is not repeated further into the future because from the day where the task was marked completed (2018-03-27 in the case) the next business day is the 2018-03-28.

In the current code of QTodoTxt2 recurring tasks repeat from the current date into the future. So if you have an old task like from 5 years ago it makes sense to increment this one into the future of today.
If the task is already in the future we have to decide how tasks should recur. Do we want tasks to recur in the future forward? Do we want this for tasks in the past too? (This means incrementing a lot of times if you want to pull a task into the future or you have to change the due date manually to future)

Possible solution 1:
Tasks that should recur and have a due date in the past are recurring in the future.
Tasks that should recur and have a due date in the future are repeated further more into the future. (This would fix the issue leftover from above)

Possible solution 2:
Tasks that should recur and have a due date in the past are recurring in the future.
Tasks that should recur and have a due date in the past are NOT repeated further more into the future. (That is the current implementation of this PR - recurring stops when task is already at the correct due date from the moment of completition)

I like solution 2, because the next time the mentioned task above is due is on the 28th May viewed from the 27th May. Why should one complete tasks that are due in the future?

**Comment by sttrebo** [comment]
I want to make sure I understand the options:
(A) Review NCMR Log +Admin @work t:2018-03-28 rec:+1b due:2018-03-28

Assuming the date is a Friday:
If I miss checking it off on the Friday, the task will still show up on Monday (late).  When I mark it as done on Monday it should increment to Tuesday (it currently increments to Saturday (ignore the 'b' for now)).

Assuming the date is a Monday:
If I mark it as done on the preceding Friday (before it is due), should it increment to Tuesday or stay with the Monday date?

My inclination is to have it increment to the Tuesday date irrespective of whether I marked it done on the due date or before the due date.  I think this matches solution #1?  In my work flow, it gives me the option of completing and marking things done before the due date and then not needing to review those repeating tasks again on the actual due date.

**Comment by topas-rec** [comment]
Need this in more detail.

> Assuming the date is a Friday:

The due date is Friday? 

> If I miss checking it off on the Friday, the task will still show up on Monday (late). When I mark it as done on Monday it should increment to Tuesday (it currently increments to Saturday (ignore the 'b' for now)).

When you mark it done which current day is it?

> Assuming the date is a Monday:

Again: Due date or current date?

If I mark it as done on the preceding Friday (before it is due), should it increment to Tuesday or stay with the Monday date?

On which day do you mark it complete?

**Comment by sttrebo** [comment]
assuming today is Friday the 28th and the tasked is dated Friday the 28th:

if today (28th) i mark the task done, it should increment to Saturday (29th), based on the '+1d' parameter or Monday (31st) if it's '+1b'.
if i wait until Monday (31st) then i mark the task (dated 28th remember) done, it should increment to Tuesday (1st), currently it would increment to Saturday (29th) or Monday (31st) depending on the recur parameter.
if it is Wednesday the 26th and i mark the task done (dated the 28th remember), then the task should increment to the either the 29th or 31st depending on the recur parameter.

For my workflow:
if it is Wednesday the 26th and i mark the task done (dated the 28th remember), then not incrementing the task to a new future date doesn't make sense to me.

**Comment by topas-rec** [comment]
That's solution 1.
I understand. I'll implement that. We'll see how it goes. If someone in the future does not agree with that they should make an issue.

**Comment by topas-rec** [comment]
I changed it partly to your suggestion. When some task is recurring now and marked as recurring from original due date (+1w) then this task now should recur relative to its original due date. (If that is far in the past and the interval is too short to push it to the future then well it'll stay in the past)
Tasks in the future which are marked as recurring relative to original due date now should recur further into the future.

I don't want to have tasks in the past - marked as recurring from original due date - to be pushed into the future because other todo.txt implementations don't do it. I think they should behave identially. I took Simpletasks from Adnroid for reference. I use it. Description from Simpletasks regarding recurring tasks links here: https://www.topydo.org/
I also tested it on Simpletasks. Created a tasks in the past (2017) and marked it as recurring every week from original due date and after completing it once it still was in 2017 but one week later.

Can you test this again for the issue that remained (recurring tasks don't increment properly)?

**Comment by oroulet** [comment]
I never use that function so I have no idea what a correct behaviour should be.... but I let you decide and then we can merge

**Comment by topas-rec** [comment]
@sttrebo : Can we merge this one? Have you tested it after my last commit?

**Comment by sttrebo** [comment]
i think so:
Had a task: (A) test123 +Personal @Work due:2018-05-01 t:2018-04-18 rec:1d

marked it as done and got:both due and t set to 2018-05-01
marked it done several additional times time and both due and t stayed at 2018-05-01
i think this is acceptable
    On Monday, April 30, 2018, 7:03:17 AM PDT, Topas <notifications@github.com> wrote:  
 
 
@sttrebo : Can we merge this one? Have you tested it after my last commit?

**Pull request merged**
