### PR TITLE
tableview, 2nd attempt

### PR DESCRIPTION
**Pull request by fuchsmich**

### CODE REVIEW

**Comment by oroulet** [comment]
Missing the tableview file I think...

**Comment by fuchsmich** [comment]
can you see it now?

**Comment by oroulet** [comment]
let me know when it is usable, and enable multiselection from the start so we do not get surprises

**Comment by fuchsmich** [comment]
It works quite well already.

Can we push the branch to upstream?
Because I would need you to implement some python code, which can handle 
multiselection (deleting, completion, etc).

e.g.

mainController.deleteTasks(arrayOfIndices)
mainController.completeTasks(arrayOfIndices)


Am 08.06.2017 um 09:45 schrieb oroulet:

**Pull request merged**
